### ISSUE TITLE
Windows 98 - Online Services folder Exception 

### ISSUE THREAD

**Issue by AO554** [HistacomUnity/Histacom2-old#3]
### Part

Online Services Desktop Icon

### Expected behavior

Exception Error

### Actual behavior

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Histacom2.OS.Win98.Windows98.desktopicons_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### Screenshots (if applicable)

https://cdn.discordapp.com/attachments/194173133165428736/564198828362956802/unknown.png

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Histacom version
2.0.3-dev

**Comment by ByteOfMelon** [comment]
Thanks, I'll fix it in the next commit.

**Comment by ByteOfMelon** [comment]
Fixed.
